### ISSUE TITLE
Interactive?

### ISSUE THREAD

**Issue by rigoletto-freebsd** [mjambon/ocamlscript#5]
Hello.

Just out of curiosity, since the subject of my question seems completely out of the scope of this project, but have you any plan to take it further to an interactive shell (like sh, csh, zsh, fish etc.)?

Would be great to have a complete OCaml solution for UNIX-like shells.

Great work! Thanks!

**Comment by mjambon** [comment]
I have no such plans, at least due to lack of time. The project is barely maintained and should be moved to ocaml-community where different people can take care of basic maintenance. See https://github.com/ocaml-community/meta/issues/25.

**Comment by rigoletto-freebsd** [comment]
Thank you for your reply. I subscribed to ocaml-community issue you pointed.

**Comment by UnixJunkie** [comment]
this issue could be closed
